import type { Metadata } from "next";
import { Bokor, Lora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import AdSense from "@/components/core/AdSense";

const bokor = Bokor({
  variable: "--font-bokor",
  subsets: ["khmer", "latin"],
  weight: ["400"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Warung Jurnalis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <AdSense pId="ca-pub-2804822668582605" />
      </head>
      <body className={`${lora.variable} ${bokor.variable} antialiased`}>
        <Navbar />
        <div className="container mx-auto">
          {children}
          {auth}
        </div>
        <Footer />
      </body>
    </html>
  );
}
